site_name: evilDoggie
nav:
  - Introduction: index.md
  - Software:
    - Doggie:
      - Introdutcion: software/doggie/intro.md
      - Get Started: software/doggie/get_started.md
    - evilDoggie:
      - Introduction: software/evil_doggie/intro.md
      - Get Started: software/evil_doggie/get_started.md
    - BLE: software/ble.md
  - Hardware:
    - Faraday: hardware/faraday.md
    - DIY:
      - Introduction: hardware/diy/intro.md
      - Microcontrollers:
        - ESP32: hardware/diy/esp32.md
        - RP2040 (Raspberry Pico): hardware/diy/rp.md
        - STM32F1 (bluepill): hardware/diy/bluepill.md
      - MCP2515 Notes: hardware/mcp.md
  - evilDoggie lab:
    - Introduction: workshop/intro.md

theme:
  name: readthedocs
