[package]
name = "evil_menu"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-io = "0.6.1"
embedded-can = "0.4.1"
menu = { version = "0.6.1", features = ["noline"] }
noline = "0.5.1"
heapless = "0.8.0"

evil_core = { version = "0.1.0", path = "../evil_core" }

[dependencies.crc-any]
version = "2.5.0"
default-features = false
