[package]
name = "doggie_ble"
version = "0.1.0"
edition = "2021"

[dependencies]
trouble-host = { version = "0.5", features = ["defmt", "peripheral"] }
bt-hci = { version = "0.6", features = ["defmt"] }
embassy-executor = { version = "0.9.1" }
embassy-futures = "0.1.2"
embassy-sync = { version = "0.7" }
embassy-time = "0.5.0"
embedded-hal = { version = "1.0", features = ["defmt-03"] }
embedded-io-async = "0.6.1"
embedded-io = { version = "0.6.1", features = ["defmt-03"] }
static_cell = { version="2" }
heapless = "0.9"
rand_core = { version = "0.9", default-features = false }
defmt = { version = "1.0"}
