name: Build and Release

on:
  push:
    tags:
      - "v*" # Trigger on tags starting with 'v' (e.g., v1.0.0)

jobs:
  build_bluepill:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        target: thumbv7m-none-eabi

    - name: Create output directory
      run: mkdir ./doggie_bluepill/bin

    - name: Build doggie bluepill UART and CAN Controller
      working-directory: ./doggie_bluepill
      run: DEFMT=off cargo build --bin doggie --release --no-default-features --features uart,int && mv ./target/thumbv7m-none-eabi/release/doggie ./bin/doggie_bluepill_uart_int

    - name: Build doggie bluepill USB and MCP2515
      working-directory: ./doggie_bluepill
      run: DEFMT=off cargo build --bin doggie --release --no-default-features --features usb,mcp && mv ./target/thumbv7m-none-eabi/release/doggie ./bin/doggie_bluepill_usb_mcp

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: doggie-bluepill-binaries
        path: |
          ./doggie_bluepill/bin/doggie_bluepill_usb_mcp
          ./doggie_bluepill/bin/doggie_bluepill_uart_int

  build_pico:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        target: thumbv6m-none-eabi

    - name: Install elf2uf2-rs
      working-directory: ./doggie_pico
      run: sudo apt update && sudo apt install libudev-dev && cargo install elf2uf2-rs

    - name: Create output directory
      run: mkdir ./doggie_pico/bin

    - name: Build Doggie for Pico with USB and BLE
      working-directory: ./doggie_pico
      run: DEFMT_LOG=off cargo build --release --bin doggie && cp ./target/thumbv6m-none-eabi/release/doggie ./bin/doggie_pico_usb_ble

    - name: Build evilDoggie for Pico with uart only
      working-directory: ./doggie_pico
      run: DEFMT_LOG=off cargo build --release --bin evil_doggie --no-default-features --features=uart && cp ./target/thumbv6m-none-eabi/release/evil_doggie ./bin/evil_doggie_pico_uart

    - name: Convert Doggie to uf2
      working-directory: ./doggie_pico/bin/
      run: elf2uf2-rs -v doggie_pico_usb_ble doggie_pico_usb_ble.uf2

    - name: Convert evilDoggie to uf2
      working-directory: ./doggie_pico/bin/
      run: elf2uf2-rs -v evil_doggie_pico_uart evil_doggie_pico_uart.uf2

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: doggie-pico-binaries
        path: |
          ./doggie_pico/bin/evil_doggie_pico_uart
          ./doggie_pico/bin/evil_doggie_pico_uart.uf2
          ./doggie_pico/bin/doggie_pico_usb_ble
          ./doggie_pico/bin/doggie_pico_usb_ble.uf2

  build_esp32:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        components: rust-src
        target: riscv32imc-unknown-none-elf

    - name: Set up espup
      uses: esp-rs/xtensa-toolchain@v1.5
      with:
        default: true
        ldproxy: true

    - name: Create output directory
      run: mkdir ./doggie_esp32/bin

    - name: Build Doggie esp32 twai,ble
      working-directory: ./doggie_esp32
      run: . $HOME/export-esp.sh && DEFMT_LOG=off cargo build --release --features=esp32 --target=xtensa-esp32-none-elf --bin doggie && cp ./target/xtensa-esp32-none-elf/release/doggie ./bin/doggie_esp32_twai_ble

    - name: Build Doggie for Faraday board
      working-directory: ./doggie_esp32
      run: . $HOME/export-esp.sh && DEFMT_LOG=off cargo build --release --no-default-features --features=esp32,faraday,twai --target=xtensa-esp32-none-elf --bin doggie && cp ./target/xtensa-esp32-none-elf/release/doggie ./bin/doggie_faraday

    - name: Build Doggie esp32c3 twai,ble
      working-directory: ./doggie_esp32
      run: . $HOME/export-esp.sh && DEFMT_LOG=off cargo build --release --features=esp32c3 --target=riscv32imc-unknown-none-elf --bin doggie && cp ./target/riscv32imc-unknown-none-elf/release/doggie ./bin/doggie_esp32c3_twai_ble 

    - name: Build evilDoggie esp32c3 ble
      working-directory: ./doggie_esp32
      run: . $HOME/export-esp.sh && DEFMT_LOG=off cargo buila d--release --features=esp32c3 --target=riscv32imc-unknown-none-elf --bin evil_doggie && cp ./target/riscv32imc-unknown-none-elf/release/evil_doggie ./bin/evil_doggie_esp32c3_ble

    - name: Build evilDoggie esp32 ble
      working-directory: ./doggie_esp32
      run: . $HOME/export-esp.sh && DEFMT_LOG=off cargo build --release --features=esp32 --target=xtensa-esp32-none-elf --bin evil_doggie && cp ./target/xtensa-esp32-none-elf/release/evil_doggie ./bin/evil_doggie_esp32_ble

    - name: Build Doggie for Faraday board
      working-directory: ./doggie_esp32
      run: . $HOME/export-esp.sh && DEFMT_LOG=off cargo build --release --no-default-features --features=esp32 --target=xtensa-esp32-none-elf --bin evil_doggie && cp ./target/xtensa-esp32-none-elf/release/evil_doggie ./bin/evil_doggie_faraday

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: doggie-esp32-binaries
        path: |
          ./doggie_esp32/bin/doggie_esp32_twai_ble
          ./doggie_esp32/bin/evil_doggie_esp32_ble
          ./doggie_esp32/bin/doggie_esp32c3_twai_ble
          ./doggie_esp32/bin/evil_doggie_esp32c3_ble
          ./doggie_esp32/bin/doggie_faraday
          ./doggie_esp32/bin/evil_doggie_faraday

  release:
    runs-on: ubuntu-latest
    needs:
    - build_bluepill
    - build_pico
    - build_esp32

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: doggie-*
        merge-multiple: true

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: doggie_bluepill_usb_mcp doggie_bluepill_uart_int doggie_pico_usb_ble doggie_pico_ble.uf2 evil_doggie_pico_uart evil_doggie_pico_uart.uf2 doggie_esp32_twai_ble doggie_esp32c3_twai_ble evil_doggie_esp32_ble evil_doggie_esp32c3_ble doggie_faraday evil_doggie_faraday
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        name: "Doggie Release ${{ github.ref_name }}"
        body: |
          This release contains the binaries for:
          - Doggie Bluepill
          - Doggie Pico
          - Doggie ESP32
          For more information about building and flashing, check `README.md`
